#!/usr/bin/env python3
"""Emit the exercise-day calendar the grader reads, from the site's own schedule.

The site already knows which exercises belong to which session — `sessions()`
in gen_schedule.py is the single source for the schedule table, the prep pages
and the lecture links. Rather than write that list a second time in the
grader's config and let the two drift, generate it here and paste the result
into `grading.toml` once.

It is a generator rather than something the grader imports at run time on
purpose: which day an exercise belongs to, and when it stops accepting work,
must be a value in a file that the instructor and the TA both read, so that
both compute the same grade from the same repo. A calendar that is re-derived
per run is a calendar that can change under a student.

    python3 utils/gen_grading_days.py                    # the days array
    python3 utils/gen_grading_days.py --closes ~/sync/cs326/oslings

With `--closes` pointing at the course repo, each day also gets the real time
its solutions shipped, taken from the first commit that added
`exercises/<name>/solution/`. That is what closes a day: after it, the answer
is public and later work cannot earn credit. Solutions ship in batches, so this
is not "the next session" and must not be guessed — through 2026-09-10 the four
Week 1-2 exercises all closed at the same minute.

Days with no solution released yet are emitted without `closes`, which the
grader reads as "still open".
"""

import argparse
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_schedule import sessions, stamp  # noqa: E402

# The router's session names, by weekday. Thursday is the lecture-section
# slot and Friday the lab slot; the grader derives this itself from
# `[[sessions]].days`, so it is only here to keep the comment honest.
WEEKDAY_SESSIONS = {"thursday": "lec-1, lec-2", "friday": "lab-1, lab-2"}


def solution_released(course: Path, exercise: str) -> str | None:
    """When `exercise`'s reference solution first reached the course repo."""
    out = subprocess.run(
        ["git", "log", "--diff-filter=A", "--reverse", "--format=%cd",
         "--date=format-local:%Y-%m-%d %H:%M", "--",
         f"exercises/{exercise}/solution"],
        cwd=course, capture_output=True, text=True,
        env={"TZ": "America/Los_Angeles", "PATH": "/usr/bin:/bin:/usr/local/bin"},
    )
    first = out.stdout.strip().splitlines()
    return first[0].strip() if first else None


def closes_for(course: Path, day: dict) -> tuple[str | None, list[str]]:
    """The earliest release among a day's exercises, and what is still unreleased.

    Earliest, not latest: once any of the day's answers is public, the day is
    no longer a fair place to earn credit.
    """
    times, pending = [], []
    for name in day["exercises"] + day["extra"]:
        when = solution_released(course, name)
        (times.append(when) if when else pending.append(name))
    return (min(times) if times else None), pending


def module_of(name: str) -> int:
    """Module 1 is Rust, commands and the bridges; module 2 is the kernel."""
    return 2 if name[:2].isdigit() and int(name[:2]) >= 30 else 1


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--closes", type=Path, metavar="COURSE_REPO",
                    help="fill in each day's close time from this repo's history")
    args = ap.parse_args()

    if args.closes and not (args.closes / "info.toml").exists():
        print(f"{args.closes} is not a course repo", file=sys.stderr)
        return 1

    days = [s for s in sessions() if s["type"] == "exercise"]
    print("# Exercise days. Generated by utils/gen_grading_days.py in the course")
    print("# site repo; `oslings class calendar --check` keeps `closes` honest.")
    print("#")
    print("# closes  when the day's solutions shipped — after that nothing counts.")
    print("# module  1 = Rust/commands/bridges, 2 = the kernel. Only needed when a")
    print("#         day's exercises span the two.")
    print("# extra   extra credit released that day; never part of the day score.")
    print("#")
    print("# Written as [[days]] blocks rather than one `days = [...]` array so")
    print("# that adding a day at the end of the file cannot silently attach it")
    print("# to whatever [table] happens to come last.")

    unreleased = []
    for d in days:
        date = stamp(d["date"])
        print(f'\n[[days]]   # {d["topic"].split(" · ")[0]}')
        print(f'date = "{date}"')
        if len({module_of(n) for n in d["exercises"]}) > 1:
            # The grader refuses a straddling day without an explicit module,
            # because guessing would move a student's weight between the two
            # Canvas groups. Oct 2 (21r + 30k) is the only one.
            print("module = 2        # 21r is module 1 and 30k module 2; the day counts as kernel")
        print("exercises = [" + ", ".join(f'"{n}"' for n in d["exercises"]) + "]")
        if d["extra"]:
            print("extra = [" + ", ".join(f'"{n}"' for n in d["extra"]) + "]")
        if args.closes:
            when, pending = closes_for(args.closes, d)
            if when:
                print(f'closes = "{when}"')
            unreleased.extend(pending)

    print(f"\n# {len(days)} exercise days", file=sys.stderr)
    if args.closes and unreleased:
        print(f"# still open (no solution released): {', '.join(unreleased)}",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
